version: "3"
services:
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: habitacion
      MONGO_INITDB_ROOT_USERNAME: habitacion
      MONGO_INITDB_ROOT_PASSWORD: habitacion